/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'rbian' at '4/25/15 11:05 PM' with Gradle 2.3
 *
 * @author rbian, @date 4/25/15 11:05 PM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
